### ISSUE TITLE
button is too big

### ISSUE THREAD

**Issue by team-orangeBlue** [XiaomiSimulator/SimulatorAssets#3]
this is unusable
![image](https://user-images.githubusercontent.com/63470411/177053733-dab2e58b-7e1b-4a3e-bd48-b60eaee5d75f.png)

where is the "05c6:9008/0e8d:0003 on boot" switch
where is unlocked switch
where is system has been destroyed switch
start screen must be updated or I flood your pull request with delete!!!!!!!!!!!!!!!!!!!!

**Comment by mfn003** [comment]
we're working on "05c6:9008/0e8d:0003 on boot" and "system has been destroyed": https://github.com/XiaomiSimulator/SimulatorAssets/commit/3952625a8081a957c598828e2c0aab40b651e4a8

**Comment by team-orangeBlue** [comment]
The wallpapers are too low resolution to be usable. An image rotating system for devices where the bigger number of the screen ratio is the length should be made.

sorry im too dumb on coding idk how to make one lol
![image](https://user-images.githubusercontent.com/63470411/177053859-71e1628f-6236-43af-a4d5-1feae7804b0d.png)

**Comment by mfn003** [comment]
i honestly have no idea what im doing + miui doesnt do that
